insert into Concelhos values (1, 'AGUEDA', 1);
insert into Concelhos values (2, 'ALBERGARIA-A-VELHA', 1);
insert into Concelhos values (3, 'ANADIA', 1);
insert into Concelhos values (4, 'AROUCA', 1);
insert into Concelhos values (5, 'AVEIRO', 1);
insert into Concelhos values (6, 'CASTELO DE PAIVA', 1);
insert into Concelhos values (7, 'ESPINHO', 1);
insert into Concelhos values (8, 'ESTARREJA', 1);
insert into Concelhos values (9, 'SANTA MARIA DA FEIRA', 1);
insert into Concelhos values (10, 'ILHAVO', 1);
insert into Concelhos values (11, 'MEALHADA', 1);
insert into Concelhos values (12, 'MURTOSA', 1);
insert into Concelhos values (13, 'OLIVEIRA DE AZEMEIS', 1);
insert into Concelhos values (14, 'OLIVEIRA DO BAIRRO', 1);
insert into Concelhos values (15, 'OVAR', 1);
insert into Concelhos values (16, 'S. JOÃO DA MADEIRA', 1);
insert into Concelhos values (17, 'SEVER DO VOUGA', 1);
insert into Concelhos values (18, 'VAGOS', 1);
insert into Concelhos values (19, 'VALE DE CAMBRA', 1);
insert into Concelhos values (1, 'ALJUSTREL', 2);
insert into Concelhos values (2, 'ALMODOVAR', 2);
insert into Concelhos values (3, 'ALVITO', 2);
insert into Concelhos values (4, 'BARRANCOS', 2);
insert into Concelhos values (5, 'BEJA', 2);
insert into Concelhos values (6, 'CASTRO VERDE', 2);
insert into Concelhos values (7, 'CUBA', 2);
insert into Concelhos values (8, 'FERREIRA DO ALENTEJO', 2);
insert into Concelhos values (9, 'MERTOLA', 2);
insert into Concelhos values (10, 'MOURA', 2);
insert into Concelhos values (11, 'ODEMIRA', 2);
insert into Concelhos values (12, 'OURIQUE', 2);
insert into Concelhos values (13, 'SERPA', 2);
insert into Concelhos values (14, 'VIDIGUEIRA', 2);
insert into Concelhos values (1, 'AMARES', 3);
insert into Concelhos values (2, 'BARCELOS', 3);
insert into Concelhos values (3, 'BRAGA', 3);
insert into Concelhos values (4, 'CABECEIRAS DE BASTO', 3);
insert into Concelhos values (5, 'CELORICO DE BASTO', 3);
insert into Concelhos values (6, 'ESPOSENDE', 3);
insert into Concelhos values (7, 'FAFE', 3);
insert into Concelhos values (8, 'GUIMARÃES', 3);
insert into Concelhos values (9, 'POVOA DE LANHOSO', 3);
insert into Concelhos values (10, 'TERRAS DE BOURO', 3);
insert into Concelhos values (11, 'VIEIRA DO MINHO', 3);
insert into Concelhos values (12, 'VILA NOVA DE FAMALICÃO', 3);
insert into Concelhos values (13, 'VILA VERDE', 3);
insert into Concelhos values (14, 'VIZELA', 3);
insert into Concelhos values (1, 'ALFANDEGA DA FE', 4);
insert into Concelhos values (2, 'BRAGANÇA', 4);
insert into Concelhos values (3, 'CARRAZEDA DE ANSIÃES', 4);
insert into Concelhos values (4, 'FREIXO DE ESPADA A CINTA', 4);
insert into Concelhos values (5, 'MACEDO DE CAVALEIROS', 4);
insert into Concelhos values (6, 'MIRANDA DO DOURO', 4);
insert into Concelhos values (7, 'MIRANDELA', 4);
insert into Concelhos values (8, 'MOGADOURO', 4);
insert into Concelhos values (9, 'TORRE DE MONCORVO', 4);
insert into Concelhos values (10, 'VILA FLOR', 4);
insert into Concelhos values (11, 'VIMIOSO', 4);
insert into Concelhos values (12, 'VINHAIS', 4);
insert into Concelhos values (1, 'BELMONTE', 5);
insert into Concelhos values (2, 'CASTELO BRANCO', 5);
insert into Concelhos values (3, 'COVILHÃ', 5);
insert into Concelhos values (4, 'FUNDÃO', 5);
insert into Concelhos values (5, 'IDANHA-A-NOVA', 5);
insert into Concelhos values (6, 'OLEIROS', 5);
insert into Concelhos values (7, 'PENAMACOR', 5);
insert into Concelhos values (8, 'PROENÇA-A-NOVA', 5);
insert into Concelhos values (9, 'SERTÃ', 5);
insert into Concelhos values (10, 'VILA DE REI', 5);
insert into Concelhos values (11, 'VILA VELHA DE RODÃO', 5);
insert into Concelhos values (1, 'ARGANIL', 6);
insert into Concelhos values (2, 'CANTANHEDE', 6);
insert into Concelhos values (3, 'COIMBRA', 6);
insert into Concelhos values (4, 'CONDEIXA-A-NOVA', 6);
insert into Concelhos values (5, 'FIGUEIRA DA FOZ', 6);
insert into Concelhos values (6, 'GOIS', 6);
insert into Concelhos values (7, 'LOUSÃ', 6);
insert into Concelhos values (8, 'MIRA', 6);
insert into Concelhos values (9, 'MIRANDA DO CORVO', 6);
insert into Concelhos values (10, 'MONTEMOR-O-VELHO', 6);
insert into Concelhos values (11, 'OLIVEIRA DO HOSPITAL', 6);
insert into Concelhos values (12, 'PAMPILHOSA DA SERRA', 6);
insert into Concelhos values (13, 'PENACOVA', 6);
insert into Concelhos values (14, 'PENELA', 6);
insert into Concelhos values (15, 'SOURE', 6);
insert into Concelhos values (16, 'TABUA', 6);
insert into Concelhos values (17, 'VILA NOVA DE POIARES', 6);
insert into Concelhos values (1, 'ALANDROAL', 7);
insert into Concelhos values (2, 'ARRAIOLOS', 7);
insert into Concelhos values (3, 'BORBA', 7);
insert into Concelhos values (4, 'ESTREMOZ', 7);
insert into Concelhos values (5, 'EVORA', 7);
insert into Concelhos values (6, 'MONTEMOR-O-NOVO', 7);
insert into Concelhos values (7, 'MORA', 7);
insert into Concelhos values (8, 'MOURÃO', 7);
insert into Concelhos values (9, 'PORTEL', 7);
insert into Concelhos values (10, 'REDONDO', 7);
insert into Concelhos values (11, 'REGUENGOS DE MONSARAZ', 7);
insert into Concelhos values (12, 'VENDAS NOVAS', 7);
insert into Concelhos values (13, 'VIANA DO ALENTEJO', 7);
insert into Concelhos values (14, 'VILA VIÇOSA', 7);
insert into Concelhos values (1, 'ALBUFEIRA', 8);
insert into Concelhos values (2, 'ALCOUTIM', 8);
insert into Concelhos values (3, 'ALJEZUR', 8);
insert into Concelhos values (4, 'CASTRO MARIM', 8);
insert into Concelhos values (5, 'FARO', 8);
insert into Concelhos values (6, 'LAGOA (ALGARVE)', 8);
insert into Concelhos values (7, 'LAGOS', 8);
insert into Concelhos values (8, 'LOULE', 8);
insert into Concelhos values (9, 'MONCHIQUE', 8);
insert into Concelhos values (10, 'OLHÃO', 8);
insert into Concelhos values (11, 'PORTIMÃO', 8);
insert into Concelhos values (12, 'S. BRAS DE ALPORTEL', 8);
insert into Concelhos values (13, 'SILVES', 8);
insert into Concelhos values (14, 'TAVIRA', 8);
insert into Concelhos values (15, 'VILA DO BISPO', 8);
insert into Concelhos values (16, 'VILA REAL DE SANTO ANTONIO', 8);
insert into Concelhos values (1, 'AGUIAR DA BEIRA', 9);
insert into Concelhos values (2, 'ALMEIDA', 9);
insert into Concelhos values (3, 'CELORICO DA BEIRA', 9);
insert into Concelhos values (4, 'FIGUEIRA DE CASTELO RODRIGO', 9);
insert into Concelhos values (5, 'FORNOS DE ALGODRES', 9);
insert into Concelhos values (6, 'GOUVEIA', 9);
insert into Concelhos values (7, 'GUARDA', 9);
insert into Concelhos values (8, 'MANTEIGAS', 9);
insert into Concelhos values (9, 'MEDA', 9);
insert into Concelhos values (10, 'PINHEL', 9);
insert into Concelhos values (11, 'SABUGAL', 9);
insert into Concelhos values (12, 'SEIA', 9);
insert into Concelhos values (13, 'TRANCOSO', 9);
insert into Concelhos values (14, 'VILA NOVA DE FOZ COA', 9);
insert into Concelhos values (1, 'ALCOBAÇA', 10);
insert into Concelhos values (2, 'ALVAIAZERE', 10);
insert into Concelhos values (3, 'ANSIÃO', 10);
insert into Concelhos values (4, 'BATALHA', 10);
insert into Concelhos values (5, 'BOMBARRAL', 10);
insert into Concelhos values (6, 'CALDAS DA RAINHA', 10);
insert into Concelhos values (7, 'CASTANHEIRA DE PERA', 10);
insert into Concelhos values (8, 'FIGUEIRO DOS VINHOS', 10);
insert into Concelhos values (9, 'LEIRIA', 10);
insert into Concelhos values (10, 'MARINHA GRANDE', 10);
insert into Concelhos values (11, 'NAZARE', 10);
insert into Concelhos values (12, 'OBIDOS', 10);
insert into Concelhos values (13, 'PEDROGÃO GRANDE', 10);
insert into Concelhos values (14, 'PENICHE', 10);
insert into Concelhos values (15, 'POMBAL', 10);
insert into Concelhos values (16, 'PORTO DE MOS', 10);
insert into Concelhos values (1, 'ALENQUER', 11);
insert into Concelhos values (2, 'ARRUDA DOS VINHOS', 11);
insert into Concelhos values (3, 'AZAMBUJA', 11);
insert into Concelhos values (4, 'CADAVAL', 11);
insert into Concelhos values (5, 'CASCAIS', 11);
insert into Concelhos values (6, 'LISBOA', 11);
insert into Concelhos values (7, 'LOURES', 11);
insert into Concelhos values (8, 'LOURINHÃ', 11);
insert into Concelhos values (9, 'MAFRA', 11);
insert into Concelhos values (10, 'OEIRAS', 11);
insert into Concelhos values (11, 'SINTRA', 11);
insert into Concelhos values (12, 'SOBRAL DE MONTE AGRAÇO', 11);
insert into Concelhos values (13, 'TORRES VEDRAS', 11);
insert into Concelhos values (14, 'VILA FRANCA DE XIRA', 11);
insert into Concelhos values (15, 'AMADORA', 11);
insert into Concelhos values (16, 'ODIVELAS', 11);
insert into Concelhos values (1, 'ALTER DO CHÃO', 12);
insert into Concelhos values (2, 'ARRONCHES', 12);
insert into Concelhos values (3, 'AVIS', 12);
insert into Concelhos values (4, 'CAMPO MAIOR', 12);
insert into Concelhos values (5, 'CASTELO DE VIDE', 12);
insert into Concelhos values (6, 'CRATO', 12);
insert into Concelhos values (7, 'ELVAS', 12);
insert into Concelhos values (8, 'FRONTEIRA', 12);
insert into Concelhos values (9, 'GAVIÃO', 12);
insert into Concelhos values (10, 'MARVÃO', 12);
insert into Concelhos values (11, 'MONFORTE', 12);
insert into Concelhos values (12, 'NISA', 12);
insert into Concelhos values (13, 'PONTE DE SOR', 12);
insert into Concelhos values (14, 'PORTALEGRE', 12);
insert into Concelhos values (15, 'SOUSEL', 12);
insert into Concelhos values (1, 'AMARANTE', 13);
insert into Concelhos values (2, 'BAIÃO', 13);
insert into Concelhos values (3, 'FELGUEIRAS', 13);
insert into Concelhos values (4, 'GONDOMAR', 13);
insert into Concelhos values (5, 'LOUSADA', 13);
insert into Concelhos values (6, 'MAIA', 13);
insert into Concelhos values (7, 'MARCO DE CANAVESES', 13);
insert into Concelhos values (8, 'MATOSINHOS', 13);
insert into Concelhos values (9, 'PAÇOS DE FERREIRA', 13);
insert into Concelhos values (10, 'PAREDES', 13);
insert into Concelhos values (11, 'PENAFIEL', 13);
insert into Concelhos values (12, 'PORTO', 13);
insert into Concelhos values (13, 'POVOA DE VARZIM', 13);
insert into Concelhos values (14, 'SANTO TIRSO', 13);
insert into Concelhos values (15, 'VALONGO', 13);
insert into Concelhos values (16, 'VILA DO CONDE', 13);
insert into Concelhos values (17, 'VILA NOVA DE GAIA', 13);
insert into Concelhos values (18, 'TROFA', 13);
insert into Concelhos values (1, 'ABRANTES', 14);
insert into Concelhos values (2, 'ALCANENA', 14);
insert into Concelhos values (3, 'ALMEIRIM', 14);
insert into Concelhos values (4, 'ALPIARÇA', 14);
insert into Concelhos values (5, 'BENAVENTE', 14);
insert into Concelhos values (6, 'CARTAXO', 14);
insert into Concelhos values (7, 'CHAMUSCA', 14);
insert into Concelhos values (8, 'CONSTANCIA', 14);
insert into Concelhos values (9, 'CORUCHE', 14);
insert into Concelhos values (10, 'ENTRONCAMENTO', 14);
insert into Concelhos values (11, 'FERREIRA DO ZEZERE', 14);
insert into Concelhos values (12, 'GOLEGÃ', 14);
insert into Concelhos values (13, 'MAÇÃO', 14);
insert into Concelhos values (14, 'RIO MAIOR', 14);
insert into Concelhos values (15, 'SALVATERRA DE MAGOS', 14);
insert into Concelhos values (16, 'SANTAREM', 14);
insert into Concelhos values (17, 'SARDOAL', 14);
insert into Concelhos values (18, 'TOMAR', 14);
insert into Concelhos values (19, 'TORRES NOVAS', 14);
insert into Concelhos values (20, 'VILA NOVA DA BARQUINHA', 14);
insert into Concelhos values (21, 'OUREM', 14);
insert into Concelhos values (1, 'ALCACER DO SAL', 15);
insert into Concelhos values (2, 'ALCOCHETE', 15);
insert into Concelhos values (3, 'ALMADA', 15);
insert into Concelhos values (4, 'BARREIRO', 15);
insert into Concelhos values (5, 'GRANDOLA', 15);
insert into Concelhos values (6, 'MOITA', 15);
insert into Concelhos values (7, 'MONTIJO', 15);
insert into Concelhos values (8, 'PALMELA', 15);
insert into Concelhos values (9, 'SANTIAGO DO CACEM', 15);
insert into Concelhos values (10, 'SEIXAL', 15);
insert into Concelhos values (11, 'SESIMBRA', 15);
insert into Concelhos values (12, 'SETUBAL', 15);
insert into Concelhos values (13, 'SINES', 15);
insert into Concelhos values (1, 'ARCOS DE VALDEVEZ', 16);
insert into Concelhos values (2, 'CAMINHA', 16);
insert into Concelhos values (3, 'MELGAÇO', 16);
insert into Concelhos values (4, 'MONÇÃO', 16);
insert into Concelhos values (5, 'PAREDES DE COURA', 16);
insert into Concelhos values (6, 'PONTE DA BARCA', 16);
insert into Concelhos values (7, 'PONTE DE LIMA', 16);
insert into Concelhos values (8, 'VALENÇA', 16);
insert into Concelhos values (9, 'VIANA DO CASTELO', 16);
insert into Concelhos values (10, 'VILA NOVA DE CERVEIRA', 16);
insert into Concelhos values (1, 'ALIJO', 17);
insert into Concelhos values (2, 'BOTICAS', 17);
insert into Concelhos values (3, 'CHAVES', 17);
insert into Concelhos values (4, 'MESÃO FRIO', 17);
insert into Concelhos values (5, 'MONDIM DE BASTO', 17);
insert into Concelhos values (6, 'MONTALEGRE', 17);
insert into Concelhos values (7, 'MURÇA', 17);
insert into Concelhos values (8, 'PESO DA REGUA', 17);
insert into Concelhos values (9, 'RIBEIRA DE PENA', 17);
insert into Concelhos values (10, 'SABROSA', 17);
insert into Concelhos values (11, 'SANTA MARTA DE PENAGUIÃO', 17);
insert into Concelhos values (12, 'VALPAÇOS', 17);
insert into Concelhos values (13, 'VILA POUCA DE AGUIAR', 17);
insert into Concelhos values (14, 'VILA REAL', 17);
insert into Concelhos values (1, 'ARMAMAR', 18);
insert into Concelhos values (2, 'CARREGAL DO SAL', 18);
insert into Concelhos values (3, 'CASTRO DAIRE', 18);
insert into Concelhos values (4, 'CINFÃES', 18);
insert into Concelhos values (5, 'LAMEGO', 18);
insert into Concelhos values (6, 'MANGUALDE', 18);
insert into Concelhos values (7, 'MOIMENTA DA BEIRA', 18);
insert into Concelhos values (8, 'MORTAGUA', 18);
insert into Concelhos values (9, 'NELAS', 18);
insert into Concelhos values (10, 'OLIVEIRA DE FRADES', 18);
insert into Concelhos values (11, 'PENALVA DO CASTELO', 18);
insert into Concelhos values (12, 'PENEDONO', 18);
insert into Concelhos values (13, 'RESENDE', 18);
insert into Concelhos values (14, 'SANTA COMBA DÃO', 18);
insert into Concelhos values (15, 'S. JOÃO DA PESQUEIRA', 18);
insert into Concelhos values (16, 'S. PEDRO DO SUL', 18);
insert into Concelhos values (17, 'SATÃO', 18);
insert into Concelhos values (18, 'SERNANCELHE', 18);
insert into Concelhos values (19, 'TABUAÇO', 18);
insert into Concelhos values (20, 'TAROUCA', 18);
insert into Concelhos values (21, 'TONDELA', 18);
insert into Concelhos values (22, 'VILA NOVA DE PAIVA', 18);
insert into Concelhos values (23, 'VISEU', 18);
insert into Concelhos values (24, 'VOUZELA', 18);
insert into Concelhos values (1, 'ANGRA DO HEROISMO', 19);
insert into Concelhos values (2, 'CALHETA (AÇORES)', 19);
insert into Concelhos values (3, 'SANTA CRUZ DA GRACIOSA', 19);
insert into Concelhos values (4, 'VELAS', 19);
insert into Concelhos values (5, 'VILA PRAIA DA VITORIA', 19);
insert into Concelhos values (1, 'CORVO', 20);
insert into Concelhos values (2, 'HORTA', 20);
insert into Concelhos values (3, 'LAJES DAS FLORES', 20);
insert into Concelhos values (4, 'LAJES DO PICO', 20);
insert into Concelhos values (5, 'MADALENA', 20);
insert into Concelhos values (6, 'SANTA CRUZ DAS FLORES', 20);
insert into Concelhos values (7, 'S. ROQUE DO PICO', 20);
insert into Concelhos values (1, 'LAGOA (AÇORES)', 21);
insert into Concelhos values (2, 'NORDESTE', 21);
insert into Concelhos values (3, 'PONTA DELGADA', 21);
insert into Concelhos values (4, 'POVOAÇÃO', 21);
insert into Concelhos values (5, 'RIBEIRA GRANDE', 21);
insert into Concelhos values (6, 'VILA FRANCA DO CAMPO', 21);
insert into Concelhos values (7, 'VILA DO PORTO', 21);
insert into Concelhos values (1, 'CALHETA (MADEIRA)', 22);
insert into Concelhos values (2, 'CAMARA DE LOBOS', 22);
insert into Concelhos values (3, 'FUNCHAL', 22);
insert into Concelhos values (4, 'MACHICO', 22);
insert into Concelhos values (5, 'PONTA DO SOL', 22);
insert into Concelhos values (6, 'PORTO MONIZ', 22);
insert into Concelhos values (7, 'PORTO SANTO', 22);
insert into Concelhos values (8, 'RIBEIRA BRAVA', 22);
insert into Concelhos values (9, 'SANTA CRUZ', 22);
insert into Concelhos values (10, 'SANTANA', 22);
insert into Concelhos values (11, 'S. VICENTE', 22);
