insert into Concelhos values (1, 'AGUEDA', 1);
insert into Concelhos values (2, 'ALBERGARIA-A-VELHA', 1);
insert into Concelhos values (3, 'ANADIA', 1);
insert into Concelhos values (4, 'AROUCA', 1);
insert into Concelhos values (5, 'AVEIRO', 1);
insert into Concelhos values (6, 'CASTELO DE PAIVA', 1);
insert into Concelhos values (7, 'ESPINHO', 1);
insert into Concelhos values (8, 'ESTARREJA', 1);
insert into Concelhos values (9, 'SANTA MARIA DA FEIRA', 1);
insert into Concelhos values (10, 'ILHAVO', 1);
insert into Concelhos values (11, 'MEALHADA', 1);
insert into Concelhos values (12, 'MURTOSA', 1);
insert into Concelhos values (13, 'OLIVEIRA DE AZEMEIS', 1);
insert into Concelhos values (14, 'OLIVEIRA DO BAIRRO', 1);
insert into Concelhos values (15, 'OVAR', 1);
insert into Concelhos values (16, 'S. JOÃO DA MADEIRA', 1);
insert into Concelhos values (17, 'SEVER DO VOUGA', 1);
insert into Concelhos values (18, 'VAGOS', 1);
insert into Concelhos values (19, 'VALE DE CAMBRA', 1);
insert into Concelhos values (20, 'ALJUSTREL', 2);
insert into Concelhos values (21, 'ALMODOVAR', 2);
insert into Concelhos values (22, 'ALVITO', 2);
insert into Concelhos values (23, 'BARRANCOS', 2);
insert into Concelhos values (24, 'BEJA', 2);
insert into Concelhos values (25, 'CASTRO VERDE', 2);
insert into Concelhos values (26, 'CUBA', 2);
insert into Concelhos values (27, 'FERREIRA DO ALENTEJO', 2);
insert into Concelhos values (28, 'MERTOLA', 2);
insert into Concelhos values (29, 'MOURA', 2);
insert into Concelhos values (30, 'ODEMIRA', 2);
insert into Concelhos values (31, 'OURIQUE', 2);
insert into Concelhos values (32, 'SERPA', 2);
insert into Concelhos values (33, 'VIDIGUEIRA', 2);
insert into Concelhos values (34, 'AMARES', 3);
insert into Concelhos values (35, 'BARCELOS', 3);
insert into Concelhos values (36, 'BRAGA', 3);
insert into Concelhos values (37, 'CABECEIRAS DE BASTO', 3);
insert into Concelhos values (38, 'CELORICO DE BASTO', 3);
insert into Concelhos values (39, 'ESPOSENDE', 3);
insert into Concelhos values (40, 'FAFE', 3);
insert into Concelhos values (41, 'GUIMARÃES', 3);
insert into Concelhos values (42, 'POVOA DE LANHOSO', 3);
insert into Concelhos values (43, 'TERRAS DE BOURO', 3);
insert into Concelhos values (44, 'VIEIRA DO MINHO', 3);
insert into Concelhos values (45, 'VILA NOVA DE FAMALICÃO', 3);
insert into Concelhos values (46, 'VILA VERDE', 3);
insert into Concelhos values (47, 'VIZELA', 3);
insert into Concelhos values (48, 'ALFANDEGA DA FE', 4);
insert into Concelhos values (49, 'BRAGANÇA', 4);
insert into Concelhos values (50, 'CARRAZEDA DE ANSIÃES', 4);
insert into Concelhos values (51, 'FREIXO DE ESPADA A CINTA', 4);
insert into Concelhos values (52, 'MACEDO DE CAVALEIROS', 4);
insert into Concelhos values (53, 'MIRANDA DO DOURO', 4);
insert into Concelhos values (54, 'MIRANDELA', 4);
insert into Concelhos values (55, 'MOGADOURO', 4);
insert into Concelhos values (56, 'TORRE DE MONCORVO', 4);
insert into Concelhos values (57, 'VILA FLOR', 4);
insert into Concelhos values (58, 'VIMIOSO', 4);
insert into Concelhos values (59, 'VINHAIS', 4);
insert into Concelhos values (60, 'BELMONTE', 5);
insert into Concelhos values (61, 'CASTELO BRANCO', 5);
insert into Concelhos values (62, 'COVILHÃ', 5);
insert into Concelhos values (63, 'FUNDÃO', 5);
insert into Concelhos values (64, 'IDANHA-A-NOVA', 5);
insert into Concelhos values (65, 'OLEIROS', 5);
insert into Concelhos values (66, 'PENAMACOR', 5);
insert into Concelhos values (67, 'PROENÇA-A-NOVA', 5);
insert into Concelhos values (68, 'SERTÃ', 5);
insert into Concelhos values (69, 'VILA DE REI', 5);
insert into Concelhos values (70, 'VILA VELHA DE RODÃO', 5);
insert into Concelhos values (71, 'ARGANIL', 6);
insert into Concelhos values (72, 'CANTANHEDE', 6);
insert into Concelhos values (73, 'COIMBRA', 6);
insert into Concelhos values (74, 'CONDEIXA-A-NOVA', 6);
insert into Concelhos values (75, 'FIGUEIRA DA FOZ', 6);
insert into Concelhos values (76, 'GOIS', 6);
insert into Concelhos values (77, 'LOUSÃ', 6);
insert into Concelhos values (78, 'MIRA', 6);
insert into Concelhos values (79, 'MIRANDA DO CORVO', 6);
insert into Concelhos values (80, 'MONTEMOR-O-VELHO', 6);
insert into Concelhos values (81, 'OLIVEIRA DO HOSPITAL', 6);
insert into Concelhos values (82, 'PAMPILHOSA DA SERRA', 6);
insert into Concelhos values (83, 'PENACOVA', 6);
insert into Concelhos values (84, 'PENELA', 6);
insert into Concelhos values (85, 'SOURE', 6);
insert into Concelhos values (86, 'TABUA', 6);
insert into Concelhos values (87, 'VILA NOVA DE POIARES', 6);
insert into Concelhos values (88, 'ALANDROAL', 7);
insert into Concelhos values (89, 'ARRAIOLOS', 7);
insert into Concelhos values (90, 'BORBA', 7);
insert into Concelhos values (91, 'ESTREMOZ', 7);
insert into Concelhos values (92, 'EVORA', 7);
insert into Concelhos values (93, 'MONTEMOR-O-NOVO', 7);
insert into Concelhos values (94, 'MORA', 7);
insert into Concelhos values (95, 'MOURÃO', 7);
insert into Concelhos values (96, 'PORTEL', 7);
insert into Concelhos values (97, 'REDONDO', 7);
insert into Concelhos values (98, 'REGUENGOS DE MONSARAZ', 7);
insert into Concelhos values (99, 'VENDAS NOVAS', 7);
insert into Concelhos values (100, 'VIANA DO ALENTEJO', 7);
insert into Concelhos values (101, 'VILA VIÇOSA', 7);
insert into Concelhos values (102, 'ALBUFEIRA', 8);
insert into Concelhos values (103, 'ALCOUTIM', 8);
insert into Concelhos values (104, 'ALJEZUR', 8);
insert into Concelhos values (105, 'CASTRO MARIM', 8);
insert into Concelhos values (106, 'FARO', 8);
insert into Concelhos values (107, 'LAGOA (ALGARVE)', 8);
insert into Concelhos values (108, 'LAGOS', 8);
insert into Concelhos values (109, 'LOULE', 8);
insert into Concelhos values (110, 'MONCHIQUE', 8);
insert into Concelhos values (111, 'OLHÃO', 8);
insert into Concelhos values (112, 'PORTIMÃO', 8);
insert into Concelhos values (113, 'S. BRAS DE ALPORTEL', 8);
insert into Concelhos values (114, 'SILVES', 8);
insert into Concelhos values (115, 'TAVIRA', 8);
insert into Concelhos values (116, 'VILA DO BISPO', 8);
insert into Concelhos values (117, 'VILA REAL DE SANTO ANTONIO', 8);
insert into Concelhos values (118, 'AGUIAR DA BEIRA', 9);
insert into Concelhos values (119, 'ALMEIDA', 9);
insert into Concelhos values (120, 'CELORICO DA BEIRA', 9);
insert into Concelhos values (121, 'FIGUEIRA DE CASTELO RODRIGO', 9);
insert into Concelhos values (122, 'FORNOS DE ALGODRES', 9);
insert into Concelhos values (123, 'GOUVEIA', 9);
insert into Concelhos values (124, 'GUARDA', 9);
insert into Concelhos values (125, 'MANTEIGAS', 9);
insert into Concelhos values (126, 'MEDA', 9);
insert into Concelhos values (127, 'PINHEL', 9);
insert into Concelhos values (128, 'SABUGAL', 9);
insert into Concelhos values (129, 'SEIA', 9);
insert into Concelhos values (130, 'TRANCOSO', 9);
insert into Concelhos values (131, 'VILA NOVA DE FOZ COA', 9);
insert into Concelhos values (132, 'ALCOBAÇA', 10);
insert into Concelhos values (133, 'ALVAIAZERE', 10);
insert into Concelhos values (134, 'ANSIÃO', 10);
insert into Concelhos values (135, 'BATALHA', 10);
insert into Concelhos values (136, 'BOMBARRAL', 10);
insert into Concelhos values (137, 'CALDAS DA RAINHA', 10);
insert into Concelhos values (138, 'CASTANHEIRA DE PERA', 10);
insert into Concelhos values (139, 'FIGUEIRO DOS VINHOS', 10);
insert into Concelhos values (140, 'LEIRIA', 10);
insert into Concelhos values (141, 'MARINHA GRANDE', 10);
insert into Concelhos values (142, 'NAZARE', 10);
insert into Concelhos values (143, 'OBIDOS', 10);
insert into Concelhos values (144, 'PEDROGÃO GRANDE', 10);
insert into Concelhos values (145, 'PENICHE', 10);
insert into Concelhos values (146, 'POMBAL', 10);
insert into Concelhos values (147, 'PORTO DE MOS', 10);
insert into Concelhos values (148, 'ALENQUER', 11);
insert into Concelhos values (149, 'ARRUDA DOS VINHOS', 11);
insert into Concelhos values (150, 'AZAMBUJA', 11);
insert into Concelhos values (151, 'CADAVAL', 11);
insert into Concelhos values (152, 'CASCAIS', 11);
insert into Concelhos values (153, 'LISBOA', 11);
insert into Concelhos values (154, 'LOURES', 11);
insert into Concelhos values (155, 'LOURINHÃ', 11);
insert into Concelhos values (156, 'MAFRA', 11);
insert into Concelhos values (157, 'OEIRAS', 11);
insert into Concelhos values (158, 'SINTRA', 11);
insert into Concelhos values (159, 'SOBRAL DE MONTE AGRAÇO', 11);
insert into Concelhos values (160, 'TORRES VEDRAS', 11);
insert into Concelhos values (161, 'VILA FRANCA DE XIRA', 11);
insert into Concelhos values (162, 'AMADORA', 11);
insert into Concelhos values (163, 'ODIVELAS', 11);
insert into Concelhos values (164, 'ALTER DO CHÃO', 12);
insert into Concelhos values (165, 'ARRONCHES', 12);
insert into Concelhos values (166, 'AVIS', 12);
insert into Concelhos values (167, 'CAMPO MAIOR', 12);
insert into Concelhos values (168, 'CASTELO DE VIDE', 12);
insert into Concelhos values (169, 'CRATO', 12);
insert into Concelhos values (170, 'ELVAS', 12);
insert into Concelhos values (171, 'FRONTEIRA', 12);
insert into Concelhos values (172, 'GAVIÃO', 12);
insert into Concelhos values (173, 'MARVÃO', 12);
insert into Concelhos values (174, 'MONFORTE', 12);
insert into Concelhos values (175, 'NISA', 12);
insert into Concelhos values (176, 'PONTE DE SOR', 12);
insert into Concelhos values (177, 'PORTALEGRE', 12);
insert into Concelhos values (178, 'SOUSEL', 12);
insert into Concelhos values (179, 'AMARANTE', 13);
insert into Concelhos values (180, 'BAIÃO', 13);
insert into Concelhos values (181, 'FELGUEIRAS', 13);
insert into Concelhos values (182, 'GONDOMAR', 13);
insert into Concelhos values (183, 'LOUSADA', 13);
insert into Concelhos values (184, 'MAIA', 13);
insert into Concelhos values (185, 'MARCO DE CANAVESES', 13);
insert into Concelhos values (186, 'MATOSINHOS', 13);
insert into Concelhos values (187, 'PAÇOS DE FERREIRA', 13);
insert into Concelhos values (188, 'PAREDES', 13);
insert into Concelhos values (189, 'PENAFIEL', 13);
insert into Concelhos values (190, 'PORTO', 13);
insert into Concelhos values (191, 'POVOA DE VARZIM', 13);
insert into Concelhos values (192, 'SANTO TIRSO', 13);
insert into Concelhos values (193, 'VALONGO', 13);
insert into Concelhos values (194, 'VILA DO CONDE', 13);
insert into Concelhos values (195, 'VILA NOVA DE GAIA', 13);
insert into Concelhos values (196, 'TROFA', 13);
insert into Concelhos values (197, 'ABRANTES', 14);
insert into Concelhos values (198, 'ALCANENA', 14);
insert into Concelhos values (199, 'ALMEIRIM', 14);
insert into Concelhos values (200, 'ALPIARÇA', 14);
insert into Concelhos values (201, 'BENAVENTE', 14);
insert into Concelhos values (202, 'CARTAXO', 14);
insert into Concelhos values (203, 'CHAMUSCA', 14);
insert into Concelhos values (204, 'CONSTANCIA', 14);
insert into Concelhos values (205, 'CORUCHE', 14);
insert into Concelhos values (206, 'ENTRONCAMENTO', 14);
insert into Concelhos values (207, 'FERREIRA DO ZEZERE', 14);
insert into Concelhos values (208, 'GOLEGÃ', 14);
insert into Concelhos values (209, 'MAÇÃO', 14);
insert into Concelhos values (210, 'RIO MAIOR', 14);
insert into Concelhos values (211, 'SALVATERRA DE MAGOS', 14);
insert into Concelhos values (212, 'SANTAREM', 14);
insert into Concelhos values (213, 'SARDOAL', 14);
insert into Concelhos values (214, 'TOMAR', 14);
insert into Concelhos values (215, 'TORRES NOVAS', 14);
insert into Concelhos values (216, 'VILA NOVA DA BARQUINHA', 14);
insert into Concelhos values (217, 'OUREM', 14);
insert into Concelhos values (218, 'ALCACER DO SAL', 15);
insert into Concelhos values (219, 'ALCOCHETE', 15);
insert into Concelhos values (220, 'ALMADA', 15);
insert into Concelhos values (221, 'BARREIRO', 15);
insert into Concelhos values (222, 'GRANDOLA', 15);
insert into Concelhos values (223, 'MOITA', 15);
insert into Concelhos values (224, 'MONTIJO', 15);
insert into Concelhos values (225, 'PALMELA', 15);
insert into Concelhos values (226, 'SANTIAGO DO CACEM', 15);
insert into Concelhos values (227, 'SEIXAL', 15);
insert into Concelhos values (228, 'SESIMBRA', 15);
insert into Concelhos values (229, 'SETUBAL', 15);
insert into Concelhos values (230, 'SINES', 15);
insert into Concelhos values (231, 'ARCOS DE VALDEVEZ', 16);
insert into Concelhos values (232, 'CAMINHA', 16);
insert into Concelhos values (233, 'MELGAÇO', 16);
insert into Concelhos values (234, 'MONÇÃO', 16);
insert into Concelhos values (235, 'PAREDES DE COURA', 16);
insert into Concelhos values (236, 'PONTE DA BARCA', 16);
insert into Concelhos values (237, 'PONTE DE LIMA', 16);
insert into Concelhos values (238, 'VALENÇA', 16);
insert into Concelhos values (239, 'VIANA DO CASTELO', 16);
insert into Concelhos values (240, 'VILA NOVA DE CERVEIRA', 16);
insert into Concelhos values (241, 'ALIJO', 17);
insert into Concelhos values (242, 'BOTICAS', 17);
insert into Concelhos values (243, 'CHAVES', 17);
insert into Concelhos values (244, 'MESÃO FRIO', 17);
insert into Concelhos values (245, 'MONDIM DE BASTO', 17);
insert into Concelhos values (246, 'MONTALEGRE', 17);
insert into Concelhos values (247, 'MURÇA', 17);
insert into Concelhos values (248, 'PESO DA REGUA', 17);
insert into Concelhos values (249, 'RIBEIRA DE PENA', 17);
insert into Concelhos values (250, 'SABROSA', 17);
insert into Concelhos values (251, 'SANTA MARTA DE PENAGUIÃO', 17);
insert into Concelhos values (252, 'VALPAÇOS', 17);
insert into Concelhos values (253, 'VILA POUCA DE AGUIAR', 17);
insert into Concelhos values (254, 'VILA REAL', 17);
insert into Concelhos values (255, 'ARMAMAR', 18);
insert into Concelhos values (256, 'CARREGAL DO SAL', 18);
insert into Concelhos values (257, 'CASTRO DAIRE', 18);
insert into Concelhos values (258, 'CINFÃES', 18);
insert into Concelhos values (259, 'LAMEGO', 18);
insert into Concelhos values (260, 'MANGUALDE', 18);
insert into Concelhos values (261, 'MOIMENTA DA BEIRA', 18);
insert into Concelhos values (262, 'MORTAGUA', 18);
insert into Concelhos values (263, 'NELAS', 18);
insert into Concelhos values (264, 'OLIVEIRA DE FRADES', 18);
insert into Concelhos values (265, 'PENALVA DO CASTELO', 18);
insert into Concelhos values (266, 'PENEDONO', 18);
insert into Concelhos values (267, 'RESENDE', 18);
insert into Concelhos values (268, 'SANTA COMBA DÃO', 18);
insert into Concelhos values (269, 'S. JOÃO DA PESQUEIRA', 18);
insert into Concelhos values (270, 'S. PEDRO DO SUL', 18);
insert into Concelhos values (271, 'SATÃO', 18);
insert into Concelhos values (272, 'SERNANCELHE', 18);
insert into Concelhos values (273, 'TABUAÇO', 18);
insert into Concelhos values (274, 'TAROUCA', 18);
insert into Concelhos values (275, 'TONDELA', 18);
insert into Concelhos values (276, 'VILA NOVA DE PAIVA', 18);
insert into Concelhos values (277, 'VISEU', 18);
insert into Concelhos values (278, 'VOUZELA', 18);
insert into Concelhos values (279, 'ANGRA DO HEROISMO', 19);
insert into Concelhos values (280, 'CALHETA (AÇORES)', 19);
insert into Concelhos values (281, 'SANTA CRUZ DA GRACIOSA', 19);
insert into Concelhos values (282, 'VELAS', 19);
insert into Concelhos values (283, 'VILA PRAIA DA VITORIA', 19);
insert into Concelhos values (284, 'CORVO', 20);
insert into Concelhos values (285, 'HORTA', 20);
insert into Concelhos values (286, 'LAJES DAS FLORES', 20);
insert into Concelhos values (287, 'LAJES DO PICO', 20);
insert into Concelhos values (288, 'MADALENA', 20);
insert into Concelhos values (289, 'SANTA CRUZ DAS FLORES', 20);
insert into Concelhos values (290, 'S. ROQUE DO PICO', 20);
insert into Concelhos values (291, 'LAGOA (AÇORES)', 21);
insert into Concelhos values (292, 'NORDESTE', 21);
insert into Concelhos values (293, 'PONTA DELGADA', 21);
insert into Concelhos values (294, 'POVOAÇÃO', 21);
insert into Concelhos values (295, 'RIBEIRA GRANDE', 21);
insert into Concelhos values (296, 'VILA FRANCA DO CAMPO', 21);
insert into Concelhos values (297, 'VILA DO PORTO', 21);
insert into Concelhos values (298, 'CALHETA (MADEIRA)', 22);
insert into Concelhos values (299, 'CAMARA DE LOBOS', 22);
insert into Concelhos values (300, 'FUNCHAL', 22);
insert into Concelhos values (301, 'MACHICO', 22);
insert into Concelhos values (302, 'PONTA DO SOL', 22);
insert into Concelhos values (303, 'PORTO MONIZ', 22);
insert into Concelhos values (304, 'PORTO SANTO', 22);
insert into Concelhos values (305, 'RIBEIRA BRAVA', 22);
insert into Concelhos values (306, 'SANTA CRUZ', 22);
insert into Concelhos values (307, 'SANTANA', 22);
insert into Concelhos values (308, 'S. VICENTE', 22);
