insert into Distrito (Id,Nome) values (1, 'AVEIRO');
insert into Distrito (Id,Nome) values (2, 'BEJA');
insert into Distrito (Id,Nome) values (3, 'BRAGA');
insert into Distrito (Id,Nome) values (4, 'BRAGANCA');
insert into Distrito (Id,Nome) values (5, 'C BRANCO');
insert into Distrito (Id,Nome) values (6, 'COIMBRA');
insert into Distrito (Id,Nome) values (7, 'EVORA');
insert into Distrito (Id,Nome) values (8, 'FARO');
insert into Distrito (Id,Nome) values (9, 'GUARDA');
insert into Distrito (Id,Nome) values (10, 'LEIRIA');
insert into Distrito (Id,Nome) values (11, 'LISBOA');
insert into Distrito (Id,Nome) values (12, 'PORTALEGRE');
insert into Distrito (Id,Nome) values (13, 'PORTO');
insert into Distrito (Id,Nome) values (14, 'SANTAREM');
insert into Distrito (Id,Nome) values (15, 'SETUBAL');
insert into Distrito (Id,Nome) values (16, 'VIANA DO CASTELO');
insert into Distrito (Id,Nome) values (17, 'VILA REAL');
insert into Distrito (Id,Nome) values (18, 'VISEU');
insert into Distrito (Id,Nome) values (19, 'ANGRA DO HEROISMO');
insert into Distrito (Id,Nome) values (20, 'HORTA');
insert into Distrito (Id,Nome) values (21, 'PONTA DELGADA');
insert into Distrito (Id,Nome) values (22, 'FUNCHAL');
