insert into Distrito values (1, 'AVEIRO');
insert into Distrito values (2, 'BEJA');
insert into Distrito values (3, 'BRAGA');
insert into Distrito values (4, 'BRAGANCA');
insert into Distrito values (5, 'C BRANCO');
insert into Distrito values (6, 'COIMBRA');
insert into Distrito values (7, 'EVORA');
insert into Distrito values (8, 'FARO');
insert into Distrito values (9, 'GUARDA');
insert into Distrito values (10, 'LEIRIA');
insert into Distrito values (11, 'LISBOA');
insert into Distrito values (12, 'PORTALEGRE');
insert into Distrito values (13, 'PORTO');
insert into Distrito values (14, 'SANTAREM');
insert into Distrito values (15, 'SETUBAL');
insert into Distrito values (16, 'VIANA DO CASTELO');
insert into Distrito values (17, 'VILA REAL');
insert into Distrito values (18, 'VISEU');
insert into Distrito values (19, 'ANGRA DO HEROISMO');
insert into Distrito values (20, 'HORTA');
insert into Distrito values (21, 'PONTA DELGADA');
insert into Distrito values (22, 'FUNCHAL');
